name: 'Deploy Commit JAR:'
description: 'Deploy Commit JAR'
inputs:
  commit:
    description: 'Commit ID to deploy'
    required: true

runs:
  using: "composite"
  steps:

    - name: Checkout Commit
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.commit }}

    - name: Echo prueba
      run: cat ./todo
      shell: bash