name: Deploy JAR Pipeline

on:
  workflow_call:
    inputs:
      commit:
        description: 'Commit ID to deploy'
        required: false
        type: string
      version:
        description: 'Version to deploy'
        required: false
        type: string
jobs:
  deploy-jar:
    if: ${{ github.event.workflow == '.github/workflows/create-release.yml' }}
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy latest JAR
      if: ${{ inputs.commit }} == ''
      run: |
        echo ${{ inputs.commit }}
        echo ${{ inputs.version }}

    - name: Deploy commit JAR
      if: ${{ inputs.commit }} != ''
      run: |
        echo ${{ inputs.commit }}
        echo ${{ inputs.version }}

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: eu-west-3

    # - name: Create Secrets
    #   uses: 1arp/create-a-file-action@0.4.5
    #   with:
    #     path: 'src/main/resources'
    #     is AbsolutePath: false
    #     file: 'application-secret.properties'
    #     content: |
    #       riot.api.key=${{ secrets.RIOT_API_KEY }}
    #       disc.api.key=${{ secrets.DISCORD_API_KEY }}

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'adopt'
    #     cache: maven

    # - name: Build with Maven
    #   run: mvn clean package