name: Deploy JAR Pipeline

on:
  workflow_dispatch:

jobs:
  Initial-Set-Up:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create Secrets
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: 'src/main/resources'
          is AbsolutePath: false
          file: 'application-secret.properties'
          content: |
            riot.api.key=${{ secrets.RIOT_API_KEY }}
            disc.api.key=${{ secrets.DISCORD_API_KEY }}
            admin.ids=${{ secrets.DISCORD_ADMIN_IDS }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn clean test
        
      - name: Build with Maven
        run: mvn clean package

      - name: Set up SSH key
        env:
          EC2_PEM_KEY: ${{ secrets.RANKY_EC2_PEM_KEY }}
        run: |
          echo "$EC2_PEM_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
      
      - name: Add EC2 to known hosts
        env:
          EC2_IP_ADDRESS: ${{ secrets.RANKY_EC2_IP_ADDRESS }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_IP_ADDRESS >> ~/.ssh/known_hosts

      - name: Transfer files to EC2
        env:
          EC2_IP_ADDRESS: ${{ secrets.RANKY_EC2_IP_ADDRESS }}
          HOST: "ec2-user@${{ secrets.RANKY_EC2_IP_ADDRESS }}"
        run: |
          scp -i ec2_key.pem ./target/Ranky.jar $HOST:/home/ec2-user/Ranky.jar
          scp -i ec2_key.pem -r ./target/classes/config $HOST:/home/ec2-user/config

      - name: Update Docker container
        env:
          EC2_IP_ADDRESS: ${{ secrets.RANKY_EC2_IP_ADDRESS }}
          HOST: "ec2-user@${{ secrets.RANKY_EC2_IP_ADDRESS }}"
          CONTAINER_NAME: "ranky-app"
          EC2_JAR_PATH: "/home/ec2-user/Ranky.jar"
          EC2_CONFIG_PATH: "/home/ec2-user/config"
          CONTAINER_JAR_PATH: "./app/Ranky.jar"
          CONTAINER_CONFIG_PATH: "./app/classes/config"
        run: |
          ssh -i ec2_key.pem $HOST "sudo docker stop $CONTAINER_NAME"
          ssh -i ec2_key.pem $HOST "sudo docker cp $EC2_JAR_PATH $CONTAINER_NAME:$CONTAINER_JAR_PATH"
          ssh -i ec2_key.pem $HOST "sudo docker cp $EC2_CONFIG_PATH $CONTAINER_NAME:$CONTAINER_CONFIG_PATH"
          ssh -i ec2_key.pem $HOST "sudo docker start $CONTAINER_NAME"
          ssh -i ec2_key.pem $HOST "rm -rf $EC2_JAR_PATH"
          ssh -i ec2_key.pem $HOST "rm -rf $EC2_CONFIG_PATH"