name: Git Workflow Pipeline

on:
  push:
    branches:
      - develop
      - master
      - AWS202405

jobs:
  push-to-branches:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Configure git_config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Merge Current -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: eu-west-3

#     - name: Create Secrets
#       uses: 1arp/create-a-file-action@0.4.5
#       with:
#         path: 'src/main/resources'
#         is AbsolutePath: false
#         file: 'application-secret.properties'
#         content: |
#           riot.api.key=${{ secrets.RIOT_API_KEY }}
#           disc.api.key=${{ secrets.DISCORD_API_KEY }}

#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'adopt'
#         cache: maven

#     - name: Build with Maven
#       run: mvn clean package -DskipTests