name: Update GitHub Secrets from Files

on: 
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          echo "Contenido de la clave privada" > ranky-ec2-ssh.pem
          echo "192.168.1.100" > ranky-ec2-ip.txt

      - name: Get repo's public key
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MKGF/Ranky/actions/secrets/public-key)
            
          echo "KEY_ID=$(echo $RESPONSE | jq -r '.key_id')" >> $GITHUB_ENV
          echo "PUBLIC_KEY=$(echo $RESPONSE | jq -r '.key')" >> $GITHUB_ENV

      - name: Encrypt secrets
        run: |
          encrypt_secret() {
            echo -n "$1" | \
            openssl rsautl -encrypt -pubin -inkey <(echo "-----BEGIN PUBLIC KEY-----\n${{ env.PUBLIC_KEY }}\n-----END PUBLIC KEY-----") | \
            base64 -w0
          }

          ENCRYPTED_PEM_KEY=$(encrypt_secret "$(cat ranky-ec2-ssh.pem)")
          ENCRYPTED_IP=$(encrypt_secret "$(cat ranky-ec2-ip.txt)")

          echo "::add-mask::$ENCRYPTED_PEM_KEY"
          echo "::add-mask::$ENCRYPTED_IP"

          echo "ENCRYPTED_PEM_KEY=$ENCRYPTED_PEM_KEY" >> $GITHUB_ENV
          echo "ENCRYPTED_IP=$ENCRYPTED_IP" >> $GITHUB_ENV

      - name: Update GitHub Secrets
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/MKGF/Ranky/actions/secrets/RANKY_EC2_PEM_KEY \
               -d "{\"encrypted_value\":\"${{ env.ENCRYPTED_PEM_KEY }}\", \"key_id\":\"${{ env.KEY_ID }}\"}"

          curl -X PUT -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/MKGF/Ranky/actions/secrets/RANKY_EC2_IP_ADDRESS \
               -d "{\"encrypted_value\":\"${{ env.ENCRYPTED_IP }}\", \"key_id\":\"${{ env.KEY_ID }}\"}"
