name: triggered tests

on:
  repository_dispatch:
    types: 
      - trigger-test"
jobs:
        push-to-branches:
          runs-on: ubuntu-latest
          steps:

            - name: Print Hola
              run: echo "hola"