name: test taht triggers

on:
  workflow_dispatch:
    inputs:
      Is Release:
        required: true
        default: 'No'
        type: choice
        options:
          - Yes
          - No
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'
      
jobs:
        push-to-branches:
          runs-on: ubuntu-latest
          steps:
            - name: Imprimir los valores de los inputs
              run: |
                echo "¿Es un release? ${{ inputs.is_release }}"
                echo "Versión a desplegar: ${{ inputs.version }}"
            
            
        hola:
          uses: ./.github/workflows/test.yml