name: test taht triggers

on:
  workflow_dispatch:
    inputs:
      Is Release:
        required: true
        default: 'no'
        type: choice
        options:
          - Yes
          - No
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'
      
jobs:
        push-to-branches:
          runs-on: ubuntu-latest
          steps:
            - name: Print version
              run: |
                echo "Version: ${{ github.event.inputs.version }}"
            
            
        hola:
          uses: ./.github/workflows/test.yml