name: test taht triggers

on:
  workflow_dispatch:

jobs:
        push-to-branches:
          runs-on: ubuntu-latest
          steps:

            - name: Trigger test
              run: |
                curl -X POST -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/dispatches \
                -d '{"event_type":"trigger_test"}'